---
title: "`r Sys.Date()` - Control DSE"
author: "Benjamin Gansemer"
date: "`r Sys.Date()`"

---

```{r setup, include = FALSE}
knitr::opts_chunk$set(message = FALSE, fig.height = 5)
```

```{r libraries, include = FALSE}
library(ggplot2)
library(dplyr)
library(cowplot)
library(gridExtra)
library(writexl)
library(rJava)
library(rChoiceDialogs)
```

```{r source, include = FALSE}
source("dseR.R")
source("plotBasePeak.R")
source("plotDSE.R")
#source("renderRmd.R")

# comments for improvements 
# need to make the report more organized and reduce white space caused by plots

```

```{r get-info, include = FALSE}
#can set default/starting directory here
wkDir <- "C:\\Users\\benja\\Documents\\Postdoc\\Data\\ephys\\"

#choose output directory
outDir <- jchoose.dir(default = wkDir, "Select output directory")

# specify name of experiment (example: 20220805-DSE)
expName <- "230606-control"

#renderRmd(outDir, expName)

```

```{r modify-ggplot-theme, include = FALSE}
# generate new ggplot theme for plots
theme_BG <- function(base_size = 14){
  theme_bw(base_size = base_size) %+replace%
    theme(
      plot.title = element_text(size = rel(1), face = "bold",
                                margin = margin(0,0,5,0),
                                hjust = 0.5),
      panel.border = element_blank(),
      axis.line = element_line(color = "black"),
      axis.text = element_text(size = rel(0.70)),
      axis.title = element_text(size = rel(0.85), face = "bold"),
      legend.title = element_text(size = rel(0.7)),
      legend.text = element_text(size = rel(0.6)),
    )

}

```

### Import data
```{r get-files, warning = FALSE, include = FALSE}

preFile <- jchoose.files(default = wkDir, caption = "Select pre-depolarization file",
                        multi = FALSE)
postFile <- jchoose.files(default = wkDir, caption = "Select post-depolarization file",
                        multi = FALSE)

```

```{r run-dseR, warning = FALSE}
#run dseR to get data
allData <- dseR(preFile, postFile,
              numSweeps = 60, preAvg = 15, 
              postStart = 2, postAvg = 5)
```

### Save data to spreadsheets
```{r save-data, results = "hide"}

if (!dir.exists(outDir)) {
  dir.create(outDir)
}


# write file of calculated % DSE for individual sweeps
combinePerc <- data.frame(Sweep = allData$Cell1$Sweep, 
                          Time = allData$Cell1$Time)
combinePerc <- cbind(combinePerc, 
                     allData$preDepolPerc[,!names(allData$preDepolPerc) %in% 
                                  c("avgPerc", "percSE")])

combinePerc <- cbind(combinePerc, 
                     allData$postDepolPerc[,!names(allData$postDepolPerc)
                                           %in% c("avgPerc", "percSE")])

write_xlsx(combinePerc, path = paste0(outDir, "/", expName, "_percDSE.xlsx"))

# write files for all data
lapply(names(allData), function(x) {
  write_xlsx(allData[[x]], 
             path = paste0(outDir, "/", expName, "_", x, ".xlsx"))
})
```

### Prestimulus baseline amplitude for all cells
```{r plot-baseline, echo = FALSE}
#need to allow for different times/stimulation frequency
combinedData <- as.data.frame(allData$combined)

allBaseline <- c(combinedData$PreBaselineAmp, combinedData$PostBaselineAmp)
minBaseline <- round(min(allBaseline), digits = -1) - 5
maxBaseline <- round(max(allBaseline), digits = -1) + 5

preBaselinePlot <- ggplot(combinedData,
                   aes(Time, PreBaselineAmp, color = data.frame)) +
  geom_point(size = 2) +
  scale_color_brewer(palette = "Dark2") +
  labs(title = "Predepolarization baseline", x = "Time (s)",
       y = "Baseline Amplitude (pA)") +
  theme_BG() +
  scale_x_continuous(limits = c(0, 120), breaks = seq(0, 120, 15),
                     expand = c(0,0)) +
  scale_y_continuous(limits = c(minBaseline, maxBaseline),
                     breaks = seq(minBaseline, maxBaseline, 50),
                     expand = c(0,0))

postBaselinePlot <- ggplot(combinedData,
                   aes(Time, PostBaselineAmp, color = data.frame)) +
  geom_point(size = 2) +
  scale_color_brewer(palette = "Dark2") +
  labs(title = "Postdepolarization baseline", x = "Time (s)",
       y = "Baseline Amplitude (pA)") +
  theme_BG() +
  scale_x_continuous(limits = c(0, 120), breaks = seq(0, 120, 15),
                     expand = c(0,0)) +
  scale_y_continuous(limits = c(minBaseline, maxBaseline),
                     breaks = seq(minBaseline, maxBaseline, 50),
                     expand = c(0,0))

```

```{r show-baseline-plots, echo = FALSE, fig.align = "center", fig.cap = "Prestimulus baseline for all cells", fig.height = 3}

tempBase <- plot_grid(preBaselinePlot + theme(legend.position = "none"),
          postBaselinePlot + theme(legend.position = "none"), 
          align = "vh", hjust = -1, nrow = 1)

baseLeg <- get_legend(preBaselinePlot + theme_BG() +
                        guides(color = guide_legend(title = "Cell")))

basePlotGrid <- plot_grid(tempBase, baseLeg, nrow = 1,
                          rel_widths = c(1, 0.1))

basePlotGrid

```


### Baseline and Peak data for individual cells
```{r plot-baseline-and-peak, echo = FALSE}
source("plotBasePeak.R")

for (cell in unique(allData$combined$data.frame)){
  #pname <- paste(cell, "Plot", sep = '')
  #assign(pname, plotBasePeak(data = as.data.frame(allData[[cell]]),
                             #plotTitle = cell))
  print(plotBasePeak(as.data.frame(allData[[cell]]), 
                     plotTitle = cell))
}

```

### Plot perscent ePSC amplitude for each cell
```{r plot-perc-inhibition, echo = FALSE}


for (cell in unique(allData$combined$data.frame)){
  print(plotDSE(as.data.frame(allData[[cell]]), 
                plotTitle = cell, preAvg = 15)) 
}


```

### Plot average percent ePSC amplitude
```{r plot-avg-perc-inhibition, echo = FALSE, fig.align = "center", fig.cap = "ePSC amplitude as percent baseline", fig.height = 4, fig.width = 5}
# may just add this to dseR
# might create new script to make a separate plot for each
# individual cell, then plot the average at the end.
# may allow for better identification of which cells
# have DSE and which don't. 
preAvg <- 15 #needs to be same as preAvg for calling dseR

# organize data for plotting
totalSweeps <- 1:(length(allData$Cell1$Sweep)+preAvg)
totalTime <- (totalSweeps-1)*1.99998

# create vector of all percent amplitudes
# start with getting pre depolarization numbers
percAmpAvg <- tail(allData$preDepolPerc$avgPerc, preAvg) 
percAmpSE <- tail(allData$preDepolPerc$percSE, preAvg)

# append post depolarization numbers
percAmpAvg <- c(percAmpAvg, allData$postDepolPerc$avgPerc)
percAmpSE <- c(percAmpSE, allData$postDepolPerc$percSE)

# create dataframe
plotPercData <- data.frame(Time = totalTime, percentAmplitude = percAmpAvg,
                           SE = percAmpSE)

percAmpPlot <- ggplot(data = plotPercData, 
                      aes(x = Time, y = percentAmplitude)) +
  geom_point() +
  geom_errorbar(aes(ymin = percentAmplitude-SE, 
                    ymax = percentAmplitude+SE),
                width = 2, position = position_dodge(0.05)) +
  scale_x_continuous(limits = c(0, 150), breaks = seq(0, 150, 30),
                     expand = expansion(mult = c(0,0), add = c(1,2))) +
  scale_y_continuous(limits = c(0, 150), breaks = seq(0, 150, 25), 
                     expand = c(0, 0)) +
  labs(x = "Time (s)", y = "ePSC amplitude (%)") +
  theme_BG()

percAmpPlot
```

```{r plot-traces, eval = FALSE, include =  FALSE}
tData <- choose.files(default = "C:/Users/benja/Documents/Postdoc/data/ephys", caption = "Select trace data file", multi = FALSE)


```

```{r clear-env, include = FALSE}
rm(list = ls())
```
